name: OS Installer
on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: |
            set -e
            echo "dont look at this, go take a coffee, this will take a while"
            sudo apt update
            sudo apt install live-build --yes
            cd live-cd
            chmod +x lbconfig
            sudo bash lbconfig
      - name: Upload Build Image
        uses: actions/upload-artifact@v3
        with:
          name: live-images
          path: live-image-amd64.hybrid.iso
          retention-days: 0